(in-package #:lwlgl.opencl)

(defun %check-cl (code operation)
  (unless (zerop code) (error "~A failed with OpenCL error code ~A." operation code)))

(defun platforms ()
  (load-opencl)
  (cffi:with-foreign-object (count :unsigned-int)
    (%check-cl (%cl-get-platform-ids 0 (cffi:null-pointer) count) "clGetPlatformIDs")
    (let ((n (cffi:mem-ref count :unsigned-int)))
      (if (zerop n) '()
          (cffi:with-foreign-object (items :pointer n)
            (%check-cl (%cl-get-platform-ids n items (cffi:null-pointer)) "clGetPlatformIDs")
            (loop for index below n collect (cffi:mem-aref items :pointer index)))))))

(defun %info-string (object param getter operation)
  (cffi:with-foreign-object (size :size)
    (%check-cl (funcall getter object param 0 (cffi:null-pointer) size) operation)
    (let ((n (cffi:mem-ref size :size)))
      (cffi:with-foreign-pointer (buffer (max 1 n))
        (%check-cl (funcall getter object param n buffer (cffi:null-pointer)) operation)
        (cffi:foreign-string-to-lisp buffer :count (max 0 (1- n)))))))

(defun platform-info (platform param)
  (%info-string platform param #'%cl-get-platform-info "clGetPlatformInfo"))

(defun platform-summary (platform)
  (list :name (platform-info platform platform-name)
        :vendor (platform-info platform platform-vendor)
        :version (platform-info platform platform-version)
        :profile (platform-info platform platform-profile)
        :extensions (platform-info platform platform-extensions)))

(defun devices (platform &optional (type device-type-all))
  (cffi:with-foreign-object (count :unsigned-int)
    (let ((code (%cl-get-device-ids platform type 0 (cffi:null-pointer) count)))
      ;; CL_DEVICE_NOT_FOUND (-1) means an empty list for the requested category.
      (when (= code -1) (return-from devices '()))
      (%check-cl code "clGetDeviceIDs"))
    (let ((n (cffi:mem-ref count :unsigned-int)))
      (if (zerop n) '()
          (cffi:with-foreign-object (items :pointer n)
            (%check-cl (%cl-get-device-ids platform type n items (cffi:null-pointer)) "clGetDeviceIDs")
            (loop for index below n collect (cffi:mem-aref items :pointer index)))))))

(defun device-info (device param)
  (%info-string device param #'%cl-get-device-info "clGetDeviceInfo"))

(defun %device-scalar (device param type)
  (cffi:with-foreign-object (value type)
    (%check-cl (%cl-get-device-info device param (cffi:foreign-type-size type) value (cffi:null-pointer))
               "clGetDeviceInfo")
    (cffi:mem-ref value type)))

(defun device-info-uint (device param) (%device-scalar device param :unsigned-int))
(defun device-info-ulong (device param) (%device-scalar device param :uint64))
(defun device-info-size (device param) (%device-scalar device param :size))
(defun device-info-bool (device param) (not (zerop (device-info-uint device param))))

(defun device-summary (device)
  (list :name (device-info device device-name)
        :vendor (device-info device device-vendor)
        :vendor-id (device-info-uint device device-vendor-id)
        :version (device-info device device-version)
        :driver-version (device-info device driver-version)
        :profile (device-info device device-profile)
        :type (device-info-ulong device device-type)
        :compute-units (device-info-uint device device-max-compute-units)
        :max-work-group-size (device-info-size device device-max-work-group-size)
        :max-clock-mhz (device-info-uint device device-max-clock-frequency)
        :global-memory-bytes (device-info-ulong device device-global-mem-size)
        :local-memory-bytes (device-info-ulong device device-local-mem-size)
        :available (device-info-bool device device-available)
        :extensions (device-info device device-extensions)))

(defun opencl-report ()
  "Returns platform summaries with device summaries nested under :DEVICES."
  (mapcar (lambda (platform)
            (append (platform-summary platform)
                    (list :devices (mapcar #'device-summary (devices platform)))))
          (platforms)))
