(in-package #:lwlgl.glfw)

(register-native-module
 :glfw
 (platform-library-names
  :windows '("glfw3.dll" "glfw.dll")
  :macos '("libglfw.3.dylib" "libglfw.dylib")
  :linux '("libglfw.so.3" "libglfw.so")))

(defconstant true 1)
(defconstant false 0)
(defconstant press 1)
(defconstant release 0)
(defconstant repeat 2)

;; GLFW initialization hints / runtime platforms.
;; GLFW_PLATFORM was added in 3.4; GLFW_WAYLAND_LIBDECOR in 3.3.9.
(defconstant init-platform #x00050003)
(defconstant wayland-libdecor #x00053001)
(defconstant any-platform #x00060000)
(defconstant platform-win32 #x00060001)
(defconstant platform-cocoa #x00060002)
(defconstant platform-wayland #x00060003)
(defconstant platform-x11 #x00060004)
(defconstant platform-null #x00060005)
(defconstant wayland-prefer-libdecor #x00038001)
(defconstant wayland-disable-libdecor #x00038002)

(defparameter *glfw-platform-preference* :auto
  "Runtime GLFW platform preference: :AUTO, :X11, :WAYLAND or :NULL.
The environment variable LWLGL_GLFW_PLATFORM overrides this value.")
(defparameter *disable-wayland-libdecor* t
  "When true, disable GLFW's optional libdecor plugin on Wayland by default.
Set LWLGL_GLFW_LIBDECOR=prefer to opt back in.")

(defconstant key-unknown -1)
(defconstant key-space 32)
(defconstant key-apostrophe 39)
(defconstant key-comma 44)
(defconstant key-minus 45)
(defconstant key-period 46)
(defconstant key-slash 47)
(defconstant key-0 48)
(defconstant key-1 49)
(defconstant key-2 50)
(defconstant key-3 51)
(defconstant key-4 52)
(defconstant key-5 53)
(defconstant key-6 54)
(defconstant key-7 55)
(defconstant key-8 56)
(defconstant key-9 57)
(defconstant key-a 65)
(defconstant key-b 66)
(defconstant key-c 67)
(defconstant key-d 68)
(defconstant key-e 69)
(defconstant key-f 70)
(defconstant key-g 71)
(defconstant key-h 72)
(defconstant key-i 73)
(defconstant key-j 74)
(defconstant key-k 75)
(defconstant key-l 76)
(defconstant key-m 77)
(defconstant key-n 78)
(defconstant key-o 79)
(defconstant key-p 80)
(defconstant key-q 81)
(defconstant key-r 82)
(defconstant key-s 83)
(defconstant key-t 84)
(defconstant key-u 85)
(defconstant key-v 86)
(defconstant key-w 87)
(defconstant key-x 88)
(defconstant key-y 89)
(defconstant key-z 90)
(defconstant key-escape 256)
(defconstant key-enter 257)
(defconstant key-tab 258)
(defconstant key-backspace 259)
(defconstant key-insert 260)
(defconstant key-delete 261)
(defconstant key-right 262)
(defconstant key-left 263)
(defconstant key-down 264)
(defconstant key-up 265)
(defconstant key-page-up 266)
(defconstant key-page-down 267)
(defconstant key-home 268)
(defconstant key-end 269)
(defconstant key-f1 290)
(defconstant key-f2 291)
(defconstant key-f3 292)
(defconstant key-f4 293)
(defconstant key-f5 294)
(defconstant key-f6 295)
(defconstant key-f7 296)
(defconstant key-f8 297)
(defconstant key-f9 298)
(defconstant key-f10 299)
(defconstant key-f11 300)
(defconstant key-f12 301)
(defconstant key-left-shift 340)
(defconstant key-left-control 341)
(defconstant key-left-alt 342)
(defconstant key-left-super 343)
(defconstant key-right-shift 344)
(defconstant key-right-control 345)
(defconstant key-right-alt 346)
(defconstant key-right-super 347)

(defconstant mod-shift #x0001)
(defconstant mod-control #x0002)
(defconstant mod-alt #x0004)
(defconstant mod-super #x0008)
(defconstant mod-caps-lock #x0010)
(defconstant mod-num-lock #x0020)

(defconstant mouse-button-left 0)
(defconstant mouse-button-right 1)
(defconstant mouse-button-middle 2)

(defconstant resizable #x00020003)
(defconstant visible #x00020004)
(defconstant decorated #x00020005)
(defconstant focused #x00020001)
(defconstant auto-iconify #x00020006)
(defconstant floating #x00020007)
(defconstant maximized #x00020008)
(defconstant center-cursor #x00020009)
(defconstant transparent-framebuffer #x0002000A)
(defconstant focus-on-show #x0002000C)
(defconstant scale-to-monitor #x0002200C)
(defconstant client-api #x00022001)
(defconstant context-version-major #x00022002)
(defconstant context-version-minor #x00022003)
(defconstant opengl-forward-compat #x00022006)
(defconstant opengl-profile #x00022008)
(defconstant no-api 0)
(defconstant opengl-api #x00030001)
(defconstant opengl-es-api #x00030002)
(defconstant opengl-core-profile #x00032001)
(defconstant opengl-compat-profile #x00032002)

(defconstant cursor #x00033001)
(defconstant sticky-keys #x00033002)
(defconstant sticky-mouse-buttons #x00033003)
(defconstant lock-key-mods #x00033004)
(defconstant raw-mouse-motion #x00033005)
(defconstant cursor-normal #x00034001)
(defconstant cursor-hidden #x00034002)
(defconstant cursor-disabled #x00034003)
(defconstant cursor-captured #x00034004)

(cffi:defcfun ("glfwGetVersion" %glfw-get-version) :void
  (major :pointer) (minor :pointer) (revision :pointer))
(cffi:defcfun ("glfwInitHint" %glfw-init-hint) :void (hint :int) (value :int))
(cffi:defcfun ("glfwGetError" %glfw-get-error) :int (description :pointer))
(cffi:defcfun ("glfwGetPlatform" %glfw-get-platform) :int)
(cffi:defcfun ("glfwInit" %glfw-init) :int)
(cffi:defcfun ("glfwTerminate" %glfw-terminate) :void)
(cffi:defcfun ("glfwGetVersionString" %glfw-get-version-string) :string)
(cffi:defcfun ("glfwDefaultWindowHints" %glfw-default-window-hints) :void)
(cffi:defcfun ("glfwWindowHint" %glfw-window-hint) :void (hint :int) (value :int))
(cffi:defcfun ("glfwCreateWindow" %glfw-create-window) :pointer
  (width :int) (height :int) (title :string) (monitor :pointer) (share :pointer))
(cffi:defcfun ("glfwDestroyWindow" %glfw-destroy-window) :void (window :pointer))
(cffi:defcfun ("glfwMakeContextCurrent" %glfw-make-context-current) :void (window :pointer))
(cffi:defcfun ("glfwGetCurrentContext" %glfw-get-current-context) :pointer)
(cffi:defcfun ("glfwSwapBuffers" %glfw-swap-buffers) :void (window :pointer))
(cffi:defcfun ("glfwSwapInterval" %glfw-swap-interval) :void (interval :int))
(cffi:defcfun ("glfwPollEvents" %glfw-poll-events) :void)
(cffi:defcfun ("glfwWaitEvents" %glfw-wait-events) :void)
(cffi:defcfun ("glfwWaitEventsTimeout" %glfw-wait-events-timeout) :void (timeout :double))
(cffi:defcfun ("glfwPostEmptyEvent" %glfw-post-empty-event) :void)
(cffi:defcfun ("glfwWindowShouldClose" %glfw-window-should-close) :int (window :pointer))
(cffi:defcfun ("glfwSetWindowShouldClose" %glfw-set-window-should-close) :void (window :pointer) (value :int))
(cffi:defcfun ("glfwGetFramebufferSize" %glfw-get-framebuffer-size) :void (window :pointer) (width :pointer) (height :pointer))
(cffi:defcfun ("glfwGetWindowSize" %glfw-get-window-size) :void (window :pointer) (width :pointer) (height :pointer))
(cffi:defcfun ("glfwSetWindowSize" %glfw-set-window-size) :void (window :pointer) (width :int) (height :int))
(cffi:defcfun ("glfwGetWindowPos" %glfw-get-window-pos) :void (window :pointer) (x :pointer) (y :pointer))
(cffi:defcfun ("glfwSetWindowPos" %glfw-set-window-pos) :void (window :pointer) (x :int) (y :int))
(cffi:defcfun ("glfwSetWindowTitle" %glfw-set-window-title) :void (window :pointer) (title :string))
(cffi:defcfun ("glfwShowWindow" %glfw-show-window) :void (window :pointer))
(cffi:defcfun ("glfwHideWindow" %glfw-hide-window) :void (window :pointer))
(cffi:defcfun ("glfwFocusWindow" %glfw-focus-window) :void (window :pointer))
(cffi:defcfun ("glfwIconifyWindow" %glfw-iconify-window) :void (window :pointer))
(cffi:defcfun ("glfwRestoreWindow" %glfw-restore-window) :void (window :pointer))
(cffi:defcfun ("glfwMaximizeWindow" %glfw-maximize-window) :void (window :pointer))
(cffi:defcfun ("glfwGetWindowAttrib" %glfw-get-window-attrib) :int (window :pointer) (attrib :int))
(cffi:defcfun ("glfwGetWindowContentScale" %glfw-get-window-content-scale) :void (window :pointer) (xscale :pointer) (yscale :pointer))
(cffi:defcfun ("glfwGetWindowOpacity" %glfw-get-window-opacity) :float (window :pointer))
(cffi:defcfun ("glfwSetWindowOpacity" %glfw-set-window-opacity) :void (window :pointer) (opacity :float))
(cffi:defcfun ("glfwRequestWindowAttention" %glfw-request-window-attention) :void (window :pointer))
(cffi:defcfun ("glfwGetTime" %glfw-get-time) :double)
(cffi:defcfun ("glfwSetTime" %glfw-set-time) :void (time :double))
(cffi:defcfun ("glfwGetKey" %glfw-get-key) :int (window :pointer) (key :int))
(cffi:defcfun ("glfwGetMouseButton" %glfw-get-mouse-button) :int (window :pointer) (button :int))
(cffi:defcfun ("glfwGetCursorPos" %glfw-get-cursor-pos) :void (window :pointer) (x :pointer) (y :pointer))
(cffi:defcfun ("glfwSetCursorPos" %glfw-set-cursor-pos) :void (window :pointer) (x :double) (y :double))
(cffi:defcfun ("glfwGetInputMode" %glfw-get-input-mode) :int (window :pointer) (mode :int))
(cffi:defcfun ("glfwSetInputMode" %glfw-set-input-mode) :void (window :pointer) (mode :int) (value :int))
(cffi:defcfun ("glfwRawMouseMotionSupported" %glfw-raw-mouse-motion-supported) :int)
(cffi:defcfun ("glfwSetClipboardString" %glfw-set-clipboard-string) :void (window :pointer) (string :string))
(cffi:defcfun ("glfwGetClipboardString" %glfw-get-clipboard-string) :pointer (window :pointer))
(cffi:defcfun ("glfwGetProcAddress" %glfw-get-proc-address) :pointer (name :string))
(cffi:defcfun ("glfwVulkanSupported" %glfw-vulkan-supported) :int)
(cffi:defcfun ("glfwGetRequiredInstanceExtensions" %glfw-get-required-instance-extensions) :pointer (count :pointer))
(cffi:defcfun ("glfwCreateWindowSurface" %glfw-create-window-surface) :int
  (instance :pointer) (window :pointer) (allocator :pointer) (surface :pointer))

(cffi:defcfun ("glfwSetKeyCallback" %glfw-set-key-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetCharCallback" %glfw-set-char-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetFramebufferSizeCallback" %glfw-set-framebuffer-size-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetWindowSizeCallback" %glfw-set-window-size-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetCursorPosCallback" %glfw-set-cursor-pos-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetScrollCallback" %glfw-set-scroll-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetMouseButtonCallback" %glfw-set-mouse-button-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetWindowFocusCallback" %glfw-set-window-focus-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetWindowCloseCallback" %glfw-set-window-close-callback) :pointer (window :pointer) (callback :pointer))
(cffi:defcfun ("glfwSetDropCallback" %glfw-set-drop-callback) :pointer (window :pointer) (callback :pointer))

(defun %ensure-glfw () (ensure-native-module :glfw))

(defun get-version ()
  "Returns GLFW's runtime MAJOR, MINOR and REVISION as three values.
This is safe before GLFW initialization."
  (%ensure-glfw)
  (cffi:with-foreign-objects ((major :int) (minor :int) (revision :int))
    (%glfw-get-version major minor revision)
    (values (cffi:mem-ref major :int)
            (cffi:mem-ref minor :int)
            (cffi:mem-ref revision :int))))

(defun %version-at-least-p (wanted-major wanted-minor wanted-revision)
  (multiple-value-bind (major minor revision) (get-version)
    (or (> major wanted-major)
        (and (= major wanted-major)
             (or (> minor wanted-minor)
                 (and (= minor wanted-minor)
                      (>= revision wanted-revision)))))))

(defun init-hint (hint value)
  "Sets a GLFW initialization hint. Must be called before INIT."
  (%ensure-glfw)
  (%glfw-init-hint hint value)
  value)

(defun %string-choice (value)
  (and value (string-downcase (string-trim '(#\Space #\Tab #\Newline #\Return) value))))

(defun %platform-choice ()
  (let ((env (%string-choice (uiop:getenv "LWLGL_GLFW_PLATFORM"))))
    (cond ((member env '("x11") :test #'string=) :x11)
          ((member env '("wayland" "wl") :test #'string=) :wayland)
          ((member env '("null" "headless") :test #'string=) :null)
          ((member env '("auto" "") :test #'string=) :auto)
          (env (warn "Ignoring unknown LWLGL_GLFW_PLATFORM value ~S." env) :auto)
          (t *glfw-platform-preference*))))

(defun %wayland-session-p (platform-choice)
  (or (eq platform-choice :wayland)
      (and (eq platform-choice :auto)
           (string-equal (or (uiop:getenv "XDG_SESSION_TYPE") "") "wayland")
           (not (null (uiop:getenv "WAYLAND_DISPLAY"))))))

(defun %configure-init-hints ()
  "Applies LWLGL's safe GLFW initialization policy before glfwInit.
On GLFW 3.4+, LWLGL_GLFW_PLATFORM may force x11/wayland/null.
On Wayland with GLFW >= 3.3.9, libdecor is disabled by default because its
GTK plugin can be unsafe in embedded/non-C runtimes; set
LWLGL_GLFW_LIBDECOR=prefer to restore GLFW's libdecor preference."
  (let ((choice (%platform-choice)))
    ;; Runtime platform selection was added in GLFW 3.4.
    (when (%version-at-least-p 3 4 0)
      (case choice
        (:x11 (init-hint init-platform platform-x11))
        (:wayland (init-hint init-platform platform-wayland))
        (:null (init-hint init-platform platform-null))
        (otherwise nil)))
    ;; The Wayland libdecor hint was added in 3.3.9.  Disable it by default
    ;; for Wayland sessions; this avoids loading libdecor-gtk into SBCL and
    ;; other host runtimes unless the user explicitly opts in.
    (when (and (%version-at-least-p 3 3 9)
               (%wayland-session-p choice))
      (let ((mode (%string-choice (uiop:getenv "LWLGL_GLFW_LIBDECOR"))))
        (init-hint wayland-libdecor
                   (if (or (string= (or mode "") "prefer")
                           (string= (or mode "") "on")
                           (not *disable-wayland-libdecor*))
                       wayland-prefer-libdecor
                       wayland-disable-libdecor))))
    choice))

(defun last-error ()
  "Returns GLFW's last error code and description as two values, clearing it."
  (%ensure-glfw)
  (cffi:with-foreign-object (description :pointer)
    (setf (cffi:mem-ref description :pointer) (cffi:null-pointer))
    (let* ((code (%glfw-get-error description))
           (pointer (cffi:mem-ref description :pointer)))
      (values code
              (unless (cffi:null-pointer-p pointer)
                (cffi:foreign-string-to-lisp pointer))))))

(defun glfw-diagnostics ()
  "Returns a plist useful when reporting GLFW startup failures."
  (multiple-value-bind (major minor revision) (get-version)
    (list :version (list major minor revision)
          :version-string (version-string)
          :platform-preference (%platform-choice)
          :xdg-session-type (uiop:getenv "XDG_SESSION_TYPE")
          :display (uiop:getenv "DISPLAY")
          :wayland-display (uiop:getenv "WAYLAND_DISPLAY")
          :libdecor-policy (or (uiop:getenv "LWLGL_GLFW_LIBDECOR")
                               (if *disable-wayland-libdecor* "disable" "prefer")))))

(defun init ()
  (%ensure-glfw)
  (%configure-init-hints)
  (= (%glfw-init) true))
(defun terminate () (%glfw-terminate))
(defun version-string () (%ensure-glfw) (%glfw-get-version-string))
(defun default-window-hints () (%glfw-default-window-hints))
(defun window-hint (hint value) (%glfw-window-hint hint value))
(defun poll-events () (%glfw-poll-events))
(defun wait-events () (%glfw-wait-events))
(defun wait-events-timeout (timeout) (%glfw-wait-events-timeout (coerce timeout 'double-float)))
(defun post-empty-event () (%glfw-post-empty-event))
(defun get-time () (%glfw-get-time))
(defun set-time (time) (%glfw-set-time (coerce time 'double-float)))
(defun swap-interval (interval) (%glfw-swap-interval interval))
(defun get-proc-address (name) (%glfw-get-proc-address name))
(defun vulkan-supported-p ()
  (%ensure-glfw)
  (not (zerop (%glfw-vulkan-supported))))

(defun required-vulkan-instance-extensions ()
  "Returns GLFW's required Vulkan instance extension names, or NIL when Vulkan is unavailable."
  (%ensure-glfw)
  (cffi:with-foreign-object (count :unsigned-int)
    (let ((pointer (%glfw-get-required-instance-extensions count)))
      (if (cffi:null-pointer-p pointer)
          nil
          (loop for i below (cffi:mem-ref count :unsigned-int)
                for item = (cffi:mem-aref pointer :pointer i)
                collect (cffi:foreign-string-to-lisp item))))))
