(in-package #:lwlgl.examples)

(defun input-demo ()
  "Demonstrates stateful input, frame timing and cursor/scroll deltas. Use WASD and Escape."
  (lwlgl.glfw:with-glfw ()
    (lwlgl.glfw:default-window-hints)
    (lwlgl.glfw:window-hint lwlgl.glfw:context-version-major 3)
    (lwlgl.glfw:window-hint lwlgl.glfw:context-version-minor 3)
    (lwlgl.glfw:window-hint lwlgl.glfw:opengl-profile lwlgl.glfw:opengl-core-profile)
    #+darwin (lwlgl.glfw:window-hint lwlgl.glfw:opengl-forward-compat lwlgl.glfw:true)
    (lwlgl.glfw:with-window (window 800 500 "LWLGL — Input Demo")
      (lwlgl.glfw:make-context-current window)
      (lwlgl.glfw:swap-interval 1)
      (lwlgl.opengl:load-opengl)
      (let ((input (lwlgl.input:make-input-state window))
            (clock (lwlgl.util:make-frame-clock))
            (x 0.0d0) (y 0.0d0))
        (unwind-protect
             (loop until (lwlgl.glfw:window-should-close-p window)
                   do (lwlgl.input:begin-input-frame input)
                      (lwlgl.glfw:poll-events)
                      (multiple-value-bind (dt elapsed fps) (lwlgl.util:tick-frame-clock clock)
                        (declare (ignore elapsed))
                        (let ((speed (* 0.8d0 dt)))
                          (when (lwlgl.input:key-down-p input lwlgl.glfw:key-a) (decf x speed))
                          (when (lwlgl.input:key-down-p input lwlgl.glfw:key-d) (incf x speed))
                          (when (lwlgl.input:key-down-p input lwlgl.glfw:key-w) (incf y speed))
                          (when (lwlgl.input:key-down-p input lwlgl.glfw:key-s) (decf y speed)))
                        (when (lwlgl.input:key-pressed-p input lwlgl.glfw:key-escape)
                          (lwlgl.glfw:set-window-should-close window t))
                        (when (plusp fps)
                          (lwlgl.glfw:set-window-title
                           window (format nil "LWLGL — Input Demo | WASD (~,2F, ~,2F) | ~,0F FPS" x y fps))))
                      (multiple-value-bind (width height) (lwlgl.glfw:framebuffer-size window)
                        (lwlgl.opengl:gl-viewport 0 0 width height))
                      (lwlgl.opengl:gl-clear-color
                       (coerce (lwlgl.util:clamp (+ 0.12d0 (* x 0.12d0)) 0.02d0 0.35d0) 'single-float)
                       (coerce (lwlgl.util:clamp (+ 0.14d0 (* y 0.12d0)) 0.02d0 0.35d0) 'single-float)
                       0.20 1.0)
                      (lwlgl.opengl:gl-clear lwlgl.opengl:color-buffer-bit)
                      (lwlgl.glfw:swap-buffers window))
          (lwlgl.input:detach-input-state input))))))
