(in-package #:lwlgl.openal)

(defstruct wav-data
  (bytes #() :type vector)
  (sample-rate 0 :type integer)
  (channels 0 :type integer)
  (bits-per-sample 0 :type integer))

(defun %u16le (bytes offset)
  (logior (aref bytes offset) (ash (aref bytes (+ offset 1)) 8)))

(defun %u32le (bytes offset)
  (logior (aref bytes offset)
          (ash (aref bytes (+ offset 1)) 8)
          (ash (aref bytes (+ offset 2)) 16)
          (ash (aref bytes (+ offset 3)) 24)))

(defun %ascii4 (bytes offset)
  (coerce (loop for i from offset below (+ offset 4) collect (code-char (aref bytes i))) 'string))

(defun load-wav (path)
  "Loads an uncompressed PCM WAV file (8/16-bit mono/stereo) without external dependencies."
  (let* ((bytes (with-open-file (stream path :direction :input :element-type '(unsigned-byte 8))
                  (let ((data (make-array (file-length stream) :element-type '(unsigned-byte 8))))
                    (read-sequence data stream)
                    data)))
         (length (length bytes)))
    (when (< length 12) (error "WAV file is too small: ~A" path))
    (unless (and (string= (%ascii4 bytes 0) "RIFF") (string= (%ascii4 bytes 8) "WAVE"))
      (error "Not a RIFF/WAVE file: ~A" path))
    (let ((cursor 12) (format-code nil) (channels nil) (sample-rate nil)
          (bits nil) (payload nil))
      (loop while (<= (+ cursor 8) length)
            for id = (%ascii4 bytes cursor)
            for size = (%u32le bytes (+ cursor 4))
            for start = (+ cursor 8)
            for end = (+ start size)
            do (when (> end length) (error "Truncated WAV chunk ~A in ~A" id path))
               (cond
                 ((string= id "fmt ")
                  (when (< size 16) (error "Invalid WAV fmt chunk in ~A" path))
                  (setf format-code (%u16le bytes start)
                        channels (%u16le bytes (+ start 2))
                        sample-rate (%u32le bytes (+ start 4))
                        bits (%u16le bytes (+ start 14))))
                 ((string= id "data")
                  (setf payload (subseq bytes start end))))
               (setf cursor (+ end (mod size 2))))
      (unless (= (or format-code 0) 1)
        (error "Only PCM WAV is supported (format=~A)." format-code))
      (unless (member channels '(1 2))
        (error "Only mono/stereo WAV is supported (channels=~A)." channels))
      (unless (member bits '(8 16))
        (error "Only 8/16-bit PCM WAV is supported (bits=~A)." bits))
      (unless payload (error "WAV file has no data chunk: ~A" path))
      (make-wav-data :bytes payload :sample-rate sample-rate :channels channels :bits-per-sample bits))))

(defun wav-format (wav)
  (let ((channels (wav-data-channels wav))
        (bits (wav-data-bits-per-sample wav)))
    (cond ((and (= channels 1) (= bits 8)) format-mono8)
          ((and (= channels 1) (= bits 16)) format-mono16)
          ((and (= channels 2) (= bits 8)) format-stereo8)
          ((and (= channels 2) (= bits 16)) format-stereo16)
          (t (error "Unsupported WAV format: ~D channels, ~D bits." channels bits)))))

(defun play-wav (wav-or-path &key (looping-p nil) (gain-value 1.0))
  "Starts a WAV-DATA object or file path. Returns SOURCE and BUFFER."
  (let* ((wav (if (typep wav-or-path 'wav-data) wav-or-path (load-wav wav-or-path)))
         (bytes (wav-data-bytes wav))
         (buffer (gen-buffer))
         (source (gen-source)))
    (cffi:with-foreign-object (data :unsigned-char (length bytes))
      (dotimes (i (length bytes))
        (setf (cffi:mem-aref data :unsigned-char i) (aref bytes i)))
      (buffer-data buffer (wav-format wav) data (length bytes) (wav-data-sample-rate wav)))
    (source-i source buffer-binding buffer)
    (source-i source looping (if looping-p 1 0))
    (source-f source gain gain-value)
    (source-play source)
    (values source buffer)))
