(in-package #:lwlgl.math)

(defun mat4-determinant (matrix)
  (check-type matrix mat4)
  (let ((m (make-array '(4 4) :element-type 'double-float)))
    (dotimes (r 4)
      (dotimes (c 4)
        (setf (aref m r c) (coerce (mat4-ref matrix r c) 'double-float))))
    (let ((det 1.0d0) (sign 1.0d0))
      (dotimes (column 4 (* det sign))
        (let ((pivot column) (best (abs (aref m column column))))
          (loop for row from (1+ column) below 4
                for value = (abs (aref m row column))
                when (> value best) do (setf best value pivot row))
          (when (< best 1.0d-12) (return-from mat4-determinant 0.0f0))
          (unless (= pivot column)
            (dotimes (c 4) (rotatef (aref m column c) (aref m pivot c)))
            (setf sign (- sign)))
          (let ((pivot-value (aref m column column)))
            (setf det (* det pivot-value))
            (loop for row from (1+ column) below 4
                  for factor = (/ (aref m row column) pivot-value)
                  do (loop for c from column below 4
                           do (decf (aref m row c) (* factor (aref m column c)))))))))))

(defun mat4-inverse (matrix &key (epsilon 1.0d-10))
  "Returns the inverse of MATRIX using Gauss-Jordan elimination. Signals on singular matrices."
  (check-type matrix mat4)
  (let ((aug (make-array '(4 8) :element-type 'double-float :initial-element 0.0d0)))
    (dotimes (r 4)
      (dotimes (c 4)
        (setf (aref aug r c) (coerce (mat4-ref matrix r c) 'double-float)))
      (setf (aref aug r (+ 4 r)) 1.0d0))
    (dotimes (column 4)
      (let ((pivot column) (best (abs (aref aug column column))))
        (loop for row from (1+ column) below 4
              for value = (abs (aref aug row column))
              when (> value best) do (setf best value pivot row))
        (when (<= best epsilon)
          (error "Matrix is singular and cannot be inverted."))
        (unless (= pivot column)
          (dotimes (c 8) (rotatef (aref aug column c) (aref aug pivot c))))
        (let ((pivot-value (aref aug column column)))
          (dotimes (c 8) (setf (aref aug column c) (/ (aref aug column c) pivot-value))))
        (dotimes (row 4)
          (unless (= row column)
            (let ((factor (aref aug row column)))
              (unless (zerop factor)
                (dotimes (c 8)
                  (decf (aref aug row c) (* factor (aref aug column c))))))))))
    (let ((out (make-mat4)))
      (dotimes (r 4 out)
        (dotimes (c 4)
          (setf (mat4-ref out r c) (aref aug r (+ 4 c))))))))

(defstruct (aabb (:constructor %make-aabb (min max)))
  min max)

(defun aabb (minimum maximum)
  (check-type minimum vec3)
  (check-type maximum vec3)
  (%make-aabb minimum maximum))

(defun aabb-from-points (points)
  (let ((points (coerce points 'list)))
    (when (endp points) (error "AABB-FROM-POINTS requires at least one point."))
    (dolist (point points) (check-type point vec3))
    (let* ((first (first points))
           (min-x (vec3-x first)) (min-y (vec3-y first)) (min-z (vec3-z first))
           (max-x min-x) (max-y min-y) (max-z min-z))
      (dolist (point (rest points))
        (setf min-x (min min-x (vec3-x point)) min-y (min min-y (vec3-y point)) min-z (min min-z (vec3-z point))
              max-x (max max-x (vec3-x point)) max-y (max max-y (vec3-y point)) max-z (max max-z (vec3-z point))))
      (aabb (vec3 min-x min-y min-z) (vec3 max-x max-y max-z)))))

(defun aabb-center (box)
  (vec-scale (vec-add (aabb-min box) (aabb-max box)) 0.5))

(defun aabb-extents (box)
  (vec-scale (vec-sub (aabb-max box) (aabb-min box)) 0.5))

(defun aabb-size (box) (vec-sub (aabb-max box) (aabb-min box)))

(defun aabb-contains-point-p (box point)
  (and (<= (vec3-x (aabb-min box)) (vec3-x point) (vec3-x (aabb-max box)))
       (<= (vec3-y (aabb-min box)) (vec3-y point) (vec3-y (aabb-max box)))
       (<= (vec3-z (aabb-min box)) (vec3-z point) (vec3-z (aabb-max box)))))

(defun aabb-intersects-p (a b)
  (and (<= (vec3-x (aabb-min a)) (vec3-x (aabb-max b))) (>= (vec3-x (aabb-max a)) (vec3-x (aabb-min b)))
       (<= (vec3-y (aabb-min a)) (vec3-y (aabb-max b))) (>= (vec3-y (aabb-max a)) (vec3-y (aabb-min b)))
       (<= (vec3-z (aabb-min a)) (vec3-z (aabb-max b))) (>= (vec3-z (aabb-max a)) (vec3-z (aabb-min b)))))

(defun transform-aabb (matrix box)
  (let* ((mn (aabb-min box)) (mx (aabb-max box))
         (points (loop for x in (list (vec3-x mn) (vec3-x mx)) append
                       (loop for y in (list (vec3-y mn) (vec3-y mx)) append
                             (loop for z in (list (vec3-z mn) (vec3-z mx))
                                   collect (transform-point matrix (vec3 x y z)))))))
    (aabb-from-points points)))

(defstruct (ray (:constructor %make-ray (origin direction)))
  origin direction)

(defun ray (origin direction &key (normalize t))
  (check-type origin vec3)
  (check-type direction vec3)
  (%make-ray origin (if normalize (vec-normalize direction) direction)))

(defun ray-at (ray distance)
  (vec-add (ray-origin ray) (vec-scale (ray-direction ray) distance)))

(defun ray-aabb-intersection (ray box &key (minimum-distance 0.0) (maximum-distance most-positive-single-float))
  "Returns entry and exit distances as two values, or NIL when the ray misses BOX."
  (let ((tmin (coerce minimum-distance 'single-float))
        (tmax (coerce maximum-distance 'single-float))
        (origin (ray-origin ray))
        (direction (ray-direction ray))
        (minimum (aabb-min box))
        (maximum (aabb-max box)))
    (flet ((axis (o d mn mx)
             (if (< (abs d) 1.0e-8)
                 (if (<= mn o mx) (values most-negative-single-float most-positive-single-float) (values nil nil))
                 (let ((a (/ (- mn o) d)) (b (/ (- mx o) d)))
                   (values (min a b) (max a b))))))
      (dolist (values (list (list (vec3-x origin) (vec3-x direction) (vec3-x minimum) (vec3-x maximum))
                            (list (vec3-y origin) (vec3-y direction) (vec3-y minimum) (vec3-y maximum))
                            (list (vec3-z origin) (vec3-z direction) (vec3-z minimum) (vec3-z maximum))))
        (multiple-value-bind (near far) (apply #'axis values)
          (unless near (return-from ray-aabb-intersection nil))
          (setf tmin (max tmin near) tmax (min tmax far))
          (when (> tmin tmax) (return-from ray-aabb-intersection nil))))
      (values tmin tmax))))

(defun project-point (point model-view projection viewport-width viewport-height &key (viewport-x 0) (viewport-y 0))
  "Projects a world-space point to window coordinates. Returns X, Y and normalized depth."
  (check-type point vec3)
  (let* ((clip (transform-point (mat4-mul projection model-view) point))
         (x (+ viewport-x (* (+ (vec3-x clip) 1.0) 0.5 viewport-width)))
         (y (+ viewport-y (* (+ (vec3-y clip) 1.0) 0.5 viewport-height)))
         (z (* (+ (vec3-z clip) 1.0) 0.5)))
    (values x y z)))

(defun unproject-point (window-x window-y depth model-view projection viewport-width viewport-height
                         &key (viewport-x 0) (viewport-y 0))
  "Maps window coordinates and normalized depth back to world space."
  (let* ((ndc (vec3 (- (* 2.0 (/ (- window-x viewport-x) viewport-width)) 1.0)
                    (- (* 2.0 (/ (- window-y viewport-y) viewport-height)) 1.0)
                    (- (* 2.0 depth) 1.0)))
         (inverse (mat4-inverse (mat4-mul projection model-view))))
    (transform-point inverse ndc)))
