(in-package #:lwlgl.math)

(deftype mat4 () '(simple-array single-float (16)))

(defun mat4-p (object)
  (typep object 'mat4))

(defun make-mat4 (&optional values)
  "Creates a column-major 4x4 single-float matrix. VALUES must contain 16 elements."
  (if values
      (let ((result (make-array 16 :element-type 'single-float)))
        (unless (= (length values) 16)
          (error "MAKE-MAT4 requires exactly 16 values."))
        (dotimes (i 16 result)
          (setf (aref result i) (%sf (elt values i)))))
      (make-array 16 :element-type 'single-float :initial-element 0.0f0)))

(defun identity-mat4 ()
  (make-mat4 #(1 0 0 0
               0 1 0 0
               0 0 1 0
               0 0 0 1)))

(defun mat4-copy (matrix)
  (check-type matrix mat4)
  (copy-seq matrix))

(defun mat4-ref (matrix row column)
  (check-type matrix mat4)
  (unless (and (<= 0 row 3) (<= 0 column 3))
    (error "Matrix index out of range: (~D, ~D)." row column))
  (aref matrix (+ (* column 4) row)))

(defun (setf mat4-ref) (value matrix row column)
  (check-type matrix mat4)
  (unless (and (<= 0 row 3) (<= 0 column 3))
    (error "Matrix index out of range: (~D, ~D)." row column))
  (setf (aref matrix (+ (* column 4) row)) (%sf value)))

(defun mat4-mul (a b)
  "Returns A*B for column-major matrices."
  (check-type a mat4)
  (check-type b mat4)
  (let ((out (make-mat4)))
    (dotimes (column 4 out)
      (dotimes (row 4)
        (setf (mat4-ref out row column)
              (+ (* (mat4-ref a row 0) (mat4-ref b 0 column))
                 (* (mat4-ref a row 1) (mat4-ref b 1 column))
                 (* (mat4-ref a row 2) (mat4-ref b 2 column))
                 (* (mat4-ref a row 3) (mat4-ref b 3 column))))))))

(defun mat4-transpose (matrix)
  (check-type matrix mat4)
  (let ((out (make-mat4)))
    (dotimes (row 4 out)
      (dotimes (column 4)
        (setf (mat4-ref out row column) (mat4-ref matrix column row))))))

(defun translation-mat4 (x y z)
  (let ((m (identity-mat4)))
    (setf (mat4-ref m 0 3) (%sf x)
          (mat4-ref m 1 3) (%sf y)
          (mat4-ref m 2 3) (%sf z))
    m))

(defun scale-mat4 (x y &optional (z 1.0))
  (let ((m (identity-mat4)))
    (setf (mat4-ref m 0 0) (%sf x)
          (mat4-ref m 1 1) (%sf y)
          (mat4-ref m 2 2) (%sf z))
    m))

(defun rotation-x-mat4 (radians)
  (let* ((c (%sf (cos radians))) (s (%sf (sin radians))) (m (identity-mat4)))
    (setf (mat4-ref m 1 1) c (mat4-ref m 2 1) s
          (mat4-ref m 1 2) (- s) (mat4-ref m 2 2) c)
    m))

(defun rotation-y-mat4 (radians)
  (let* ((c (%sf (cos radians))) (s (%sf (sin radians))) (m (identity-mat4)))
    (setf (mat4-ref m 0 0) c (mat4-ref m 2 0) (- s)
          (mat4-ref m 0 2) s (mat4-ref m 2 2) c)
    m))

(defun rotation-z-mat4 (radians)
  (let* ((c (%sf (cos radians))) (s (%sf (sin radians))) (m (identity-mat4)))
    (setf (mat4-ref m 0 0) c (mat4-ref m 1 0) s
          (mat4-ref m 0 1) (- s) (mat4-ref m 1 1) c)
    m))

(defun orthographic-mat4 (left right bottom top near far)
  (let ((m (identity-mat4)))
    (setf (mat4-ref m 0 0) (%sf (/ 2.0 (- right left)))
          (mat4-ref m 1 1) (%sf (/ 2.0 (- top bottom)))
          (mat4-ref m 2 2) (%sf (/ -2.0 (- far near)))
          (mat4-ref m 0 3) (%sf (/ (- (+ right left)) (- right left)))
          (mat4-ref m 1 3) (%sf (/ (- (+ top bottom)) (- top bottom)))
          (mat4-ref m 2 3) (%sf (/ (- (+ far near)) (- far near))))
    m))

(defun perspective-mat4 (fov-y-radians aspect near far)
  (when (or (<= aspect 0) (<= near 0) (<= far near))
    (error "Invalid perspective parameters: aspect=~A near=~A far=~A" aspect near far))
  (let* ((f (/ 1.0 (tan (/ fov-y-radians 2.0))))
         (m (make-mat4)))
    (setf (mat4-ref m 0 0) (%sf (/ f aspect))
          (mat4-ref m 1 1) (%sf f)
          (mat4-ref m 2 2) (%sf (/ (+ far near) (- near far)))
          (mat4-ref m 2 3) (%sf (/ (* 2.0 far near) (- near far)))
          (mat4-ref m 3 2) -1.0f0)
    m))

(defun look-at-mat4 (eye target up)
  (check-type eye vec3)
  (check-type target vec3)
  (check-type up vec3)
  (let* ((forward (vec-normalize (vec-sub target eye)))
         (side (vec-normalize (vec-cross forward up)))
         (true-up (vec-cross side forward))
         (m (identity-mat4)))
    (setf (mat4-ref m 0 0) (vec3-x side)
          (mat4-ref m 1 0) (vec3-y side)
          (mat4-ref m 2 0) (vec3-z side)
          (mat4-ref m 0 1) (vec3-x true-up)
          (mat4-ref m 1 1) (vec3-y true-up)
          (mat4-ref m 2 1) (vec3-z true-up)
          (mat4-ref m 0 2) (- (vec3-x forward))
          (mat4-ref m 1 2) (- (vec3-y forward))
          (mat4-ref m 2 2) (- (vec3-z forward))
          (mat4-ref m 0 3) (- (vec-dot side eye))
          (mat4-ref m 1 3) (- (vec-dot true-up eye))
          (mat4-ref m 2 3) (vec-dot forward eye))
    m))

(defun transform-point (matrix point)
  (check-type matrix mat4)
  (check-type point vec3)
  (let* ((x (vec3-x point)) (y (vec3-y point)) (z (vec3-z point))
         (tx (+ (* (mat4-ref matrix 0 0) x) (* (mat4-ref matrix 0 1) y)
                (* (mat4-ref matrix 0 2) z) (mat4-ref matrix 0 3)))
         (ty (+ (* (mat4-ref matrix 1 0) x) (* (mat4-ref matrix 1 1) y)
                (* (mat4-ref matrix 1 2) z) (mat4-ref matrix 1 3)))
         (tz (+ (* (mat4-ref matrix 2 0) x) (* (mat4-ref matrix 2 1) y)
                (* (mat4-ref matrix 2 2) z) (mat4-ref matrix 2 3)))
         (tw (+ (* (mat4-ref matrix 3 0) x) (* (mat4-ref matrix 3 1) y)
                (* (mat4-ref matrix 3 2) z) (mat4-ref matrix 3 3))))
    (if (and (not (zerop tw)) (/= tw 1.0f0))
        (vec3 (/ tx tw) (/ ty tw) (/ tz tw))
        (vec3 tx ty tz))))

(defun transform-direction (matrix direction)
  (check-type matrix mat4)
  (check-type direction vec3)
  (let ((x (vec3-x direction)) (y (vec3-y direction)) (z (vec3-z direction)))
    (vec3 (+ (* (mat4-ref matrix 0 0) x) (* (mat4-ref matrix 0 1) y) (* (mat4-ref matrix 0 2) z))
          (+ (* (mat4-ref matrix 1 0) x) (* (mat4-ref matrix 1 1) y) (* (mat4-ref matrix 1 2) z))
          (+ (* (mat4-ref matrix 2 0) x) (* (mat4-ref matrix 2 1) y) (* (mat4-ref matrix 2 2) z)))))

(defun degrees->radians (degrees)
  (* degrees (/ pi 180.0)))

(defun radians->degrees (radians)
  (* radians (/ 180.0 pi)))
