(in-package #:lwlgl.math)

(defstruct (quat (:constructor %make-quat (x y z w)))
  (x 0.0f0 :type single-float)
  (y 0.0f0 :type single-float)
  (z 0.0f0 :type single-float)
  (w 1.0f0 :type single-float))

(defun quat (&optional (x 0.0) (y 0.0) (z 0.0) (w 1.0))
  (%make-quat (%sf x) (%sf y) (%sf z) (%sf w)))

(defun identity-quat () (quat 0 0 0 1))

(defun quat-length-squared (q)
  (check-type q quat)
  (+ (* (quat-x q) (quat-x q))
     (* (quat-y q) (quat-y q))
     (* (quat-z q) (quat-z q))
     (* (quat-w q) (quat-w q))))

(defun quat-length (q) (sqrt (quat-length-squared q)))

(defun quat-normalize (q &key (epsilon 1.0e-7))
  (let ((length (quat-length q)))
    (if (<= length epsilon)
        (identity-quat)
        (let ((inverse (/ 1.0 length)))
          (quat (* (quat-x q) inverse)
                (* (quat-y q) inverse)
                (* (quat-z q) inverse)
                (* (quat-w q) inverse))))))

(defun quat-conjugate (q)
  (check-type q quat)
  (quat (- (quat-x q)) (- (quat-y q)) (- (quat-z q)) (quat-w q)))

(defun quat-inverse (q &key (epsilon 1.0e-7))
  (let ((length-squared (quat-length-squared q)))
    (when (<= length-squared epsilon)
      (error "Cannot invert a zero-length quaternion."))
    (let ((conjugate (quat-conjugate q)))
      (quat (/ (quat-x conjugate) length-squared)
            (/ (quat-y conjugate) length-squared)
            (/ (quat-z conjugate) length-squared)
            (/ (quat-w conjugate) length-squared)))))

(defun quat-mul (a b)
  "Hamilton product A*B. Composition applies B first, then A, for column vectors."
  (check-type a quat)
  (check-type b quat)
  (let ((ax (quat-x a)) (ay (quat-y a)) (az (quat-z a)) (aw (quat-w a))
        (bx (quat-x b)) (by (quat-y b)) (bz (quat-z b)) (bw (quat-w b)))
    (quat (+ (* aw bx) (* ax bw) (* ay bz) (- (* az by)))
          (+ (* aw by) (- (* ax bz)) (* ay bw) (* az bx))
          (+ (* aw bz) (* ax by) (- (* ay bx)) (* az bw))
          (- (* aw bw) (* ax bx) (* ay by) (* az bz)))))

(defun quat-from-axis-angle (axis radians)
  (check-type axis vec3)
  (let* ((normal (vec-normalize axis))
         (half (/ radians 2.0))
         (s (sin half)))
    (quat (* (vec3-x normal) s)
          (* (vec3-y normal) s)
          (* (vec3-z normal) s)
          (cos half))))

(defun quat-from-euler (x-radians y-radians z-radians)
  "Builds a quaternion from intrinsic X/Y/Z rotations."
  (let ((qx (quat-from-axis-angle (vec3 1 0 0) x-radians))
        (qy (quat-from-axis-angle (vec3 0 1 0) y-radians))
        (qz (quat-from-axis-angle (vec3 0 0 1) z-radians)))
    (quat-normalize (quat-mul qz (quat-mul qy qx)))))

(defun quat-dot (a b)
  (check-type a quat)
  (check-type b quat)
  (+ (* (quat-x a) (quat-x b))
     (* (quat-y a) (quat-y b))
     (* (quat-z a) (quat-z b))
     (* (quat-w a) (quat-w b))))

(defun quat-slerp (a b amount)
  "Spherical interpolation along the shortest arc."
  (let* ((qa (quat-normalize a))
         (qb (quat-normalize b))
         (dot (quat-dot qa qb)))
    (when (< dot 0.0)
      (setf qb (quat (- (quat-x qb)) (- (quat-y qb)) (- (quat-z qb)) (- (quat-w qb)))
            dot (- dot)))
    (if (> dot 0.9995)
        (quat-normalize
         (quat (+ (quat-x qa) (* amount (- (quat-x qb) (quat-x qa))))
               (+ (quat-y qa) (* amount (- (quat-y qb) (quat-y qa))))
               (+ (quat-z qa) (* amount (- (quat-z qb) (quat-z qa))))
               (+ (quat-w qa) (* amount (- (quat-w qb) (quat-w qa))))))
        (let* ((theta0 (acos (max -1.0 (min 1.0 dot))))
               (theta (* theta0 amount))
               (sin-theta (sin theta))
               (sin-theta0 (sin theta0))
               (s0 (- (cos theta) (* dot (/ sin-theta sin-theta0))))
               (s1 (/ sin-theta sin-theta0)))
          (quat (+ (* s0 (quat-x qa)) (* s1 (quat-x qb)))
                (+ (* s0 (quat-y qa)) (* s1 (quat-y qb)))
                (+ (* s0 (quat-z qa)) (* s1 (quat-z qb)))
                (+ (* s0 (quat-w qa)) (* s1 (quat-w qb))))))))

(defun quat->mat4 (q)
  (let* ((n (quat-normalize q))
         (x (quat-x n)) (y (quat-y n)) (z (quat-z n)) (w (quat-w n))
         (xx (* x x)) (yy (* y y)) (zz (* z z))
         (xy (* x y)) (xz (* x z)) (yz (* y z))
         (wx (* w x)) (wy (* w y)) (wz (* w z))
         (m (identity-mat4)))
    (setf (mat4-ref m 0 0) (- 1.0 (* 2.0 (+ yy zz)))
          (mat4-ref m 1 0) (* 2.0 (+ xy wz))
          (mat4-ref m 2 0) (* 2.0 (- xz wy))
          (mat4-ref m 0 1) (* 2.0 (- xy wz))
          (mat4-ref m 1 1) (- 1.0 (* 2.0 (+ xx zz)))
          (mat4-ref m 2 1) (* 2.0 (+ yz wx))
          (mat4-ref m 0 2) (* 2.0 (+ xz wy))
          (mat4-ref m 1 2) (* 2.0 (- yz wx))
          (mat4-ref m 2 2) (- 1.0 (* 2.0 (+ xx yy))))
    m))

(defun quat-rotate-vector (q vector)
  (check-type vector vec3)
  (transform-direction (quat->mat4 q) vector))

(defun trs-mat4 (translation rotation scale)
  "Builds T*R*S from VEC3 translation, QUAT rotation and VEC3 scale."
  (check-type translation vec3)
  (check-type rotation quat)
  (check-type scale vec3)
  (mat4-mul
   (translation-mat4 (vec3-x translation) (vec3-y translation) (vec3-z translation))
   (mat4-mul (quat->mat4 rotation)
             (scale-mat4 (vec3-x scale) (vec3-y scale) (vec3-z scale)))))
