(in-package #:lwlgl.bindgen)

(defstruct binding-command
  lisp-name native-name return-type arguments (optional-p nil))

(defstruct binding-spec
  name api package revision (commands '()) (constants '()))

(defun %required (plist key context)
  (or (getf plist key)
      (error "Missing ~S in ~A." key context)))

(defun %parse-command (form)
  (make-binding-command
   :lisp-name (%required form :lisp-name "binding command")
   :native-name (%required form :native-name "binding command")
   :return-type (%required form :return-type "binding command")
   :arguments (copy-tree (or (getf form :arguments) '()))
   :optional-p (not (null (getf form :optional)))))

(defun read-binding-spec (pathname)
  "Reads a declarative binding specification with *READ-EVAL* disabled."
  (with-open-file (stream pathname :direction :input)
    (let ((*read-eval* nil)
          (form (read stream nil nil)))
      (unless form (error "Empty binding specification: ~A" pathname))
      (let ((spec
              (make-binding-spec
               :name (%required form :name "binding specification")
               :api (%required form :api "binding specification")
               :package (%required form :package "binding specification")
               :revision (%required form :revision "binding specification")
               :commands (mapcar #'%parse-command (or (getf form :commands) '()))
               :constants (copy-tree (or (getf form :constants) '())))))
        (validate-binding-spec spec)
        spec))))

(defun validate-binding-spec (spec)
  "Validates names and function signatures, returning SPEC."
  (let ((lisp-names (make-hash-table :test #'equal))
        (native-names (make-hash-table :test #'equal)))
    (dolist (command (binding-spec-commands spec))
      (unless (symbolp (binding-command-lisp-name command))
        (error "Lisp binding name must be a symbol: ~S" command))
      (unless (stringp (binding-command-native-name command))
        (error "Native binding name must be a string: ~S" command))
      (when (gethash (symbol-name (binding-command-lisp-name command)) lisp-names)
        (error "Duplicate Lisp binding name: ~S" (binding-command-lisp-name command)))
      (when (gethash (binding-command-native-name command) native-names)
        (error "Duplicate native binding name: ~S" (binding-command-native-name command)))
      (setf (gethash (symbol-name (binding-command-lisp-name command)) lisp-names) t
            (gethash (binding-command-native-name command) native-names) t)
      (dolist (argument (binding-command-arguments command))
        (unless (and (listp argument) (= (length argument) 2)
                     (symbolp (first argument)))
          (error "Invalid argument descriptor ~S for ~A."
                 argument (binding-command-native-name command)))))
    (dolist (constant (binding-spec-constants spec))
      (unless (and (listp constant) (= (length constant) 2)
                   (symbolp (first constant)) (integerp (second constant)))
        (error "Invalid constant descriptor: ~S" constant)))
    spec))

(defun %canonical-data (value)
  (cond ((keywordp value) (list :keyword (symbol-name value)))
        ((symbolp value) (list :symbol (symbol-name value)))
        ((consp value) (mapcar #'%canonical-data value))
        (t value)))

(defun %canonical-form (spec)
  (list :name (binding-spec-name spec) :api (binding-spec-api spec)
        :package (binding-spec-package spec) :revision (binding-spec-revision spec)
        :constants (binding-spec-constants spec)
        :commands
        (mapcar (lambda (command)
                  (list :lisp-name (binding-command-lisp-name command)
                        :native-name (binding-command-native-name command)
                        :return-type (binding-command-return-type command)
                        :arguments (binding-command-arguments command)
                        :optional (binding-command-optional-p command)))
                (binding-spec-commands spec))))

(defun binding-spec-fingerprint (spec)
  "Returns a deterministic 64-bit FNV-1a fingerprint of SPEC."
  (let ((hash #xcbf29ce484222325))
    (loop for character across (with-output-to-string (stream)
                                 (let ((*print-case* :downcase)
                                       (*print-pretty* nil))
                                   (write (%canonical-data (%canonical-form spec))
                                          :stream stream :readably t)))
          do (setf hash (ldb (byte 64 0)
                             (* (logxor hash (char-code character)) #x100000001b3))))
    (format nil "~16,'0X" hash)))

(defun emit-binding-source (spec &optional stream)
  "Emits deterministic Lisp source. Returns a string when STREAM is NIL."
  (flet ((emit (output)
           (format output ";;;; Generated by LWLGL bindgen; do not edit.~%")
           (format output ";;;; API: ~A; registry revision: ~A; fingerprint: ~A~2%"
                   (binding-spec-api spec) (binding-spec-revision spec)
                   (binding-spec-fingerprint spec))
           (format output "(in-package ~S)~2%" (binding-spec-package spec))
           (dolist (constant (binding-spec-constants spec))
             (format output "(defconstant ~(~A~) ~S)~%"
                     (symbol-name (first constant)) (second constant)))
           (when (binding-spec-constants spec) (terpri output))
           (dolist (command (binding-spec-commands spec))
             (format output "(define-gl-function ~(~A~) ~S ~S~%  ("
                     (symbol-name (binding-command-lisp-name command))
                     (binding-command-native-name command)
                     (binding-command-return-type command))
             (loop for argument in (binding-command-arguments command)
                   for first = t then nil
                   unless first do (write-char #\Space output)
                   do (format output "(~(~A~) ~S)" (symbol-name (first argument)) (second argument)))
             (format output ")~@[ :optional t~])~%" (binding-command-optional-p command)))))
    (if stream (emit stream) (with-output-to-string (output) (emit output)))))

(defun write-generated-binding (spec pathname)
  "Writes generated source only when content changed. Returns true on update."
  (let* ((content (emit-binding-source spec))
         (existing (and (probe-file pathname) (uiop:read-file-string pathname))))
    (unless (string= content (or existing ""))
      (ensure-directories-exist pathname)
      (with-open-file (stream pathname :direction :output :if-exists :supersede
                              :if-does-not-exist :create)
        (write-string content stream))
      t)))
